language: node_js
node_js:
  - "6.2.0"
before_install:
  - export DISPLAY=:99.0
before_script:
  - npm install karma jasmine-core karma-jasmine karma-phantomjs-launcher phantomjs-prebuilt
script: node_modules/karma/bin/karma start test/specs/*.js --browsers PhantomJS --single-run
